version: '3.8'

services:
  
  web:
    build: ./web

    ports:
      - "5000:5000"

    environment:
      - DB_HOST=db
      - DB_PASSWORD=minhasenha
      - CACHE_HOST=cache

    depends_on:
      - db
      - cache


  db:
    image: postgres:latest

    environment:
      - POSTGRES_PASSWORD=minhasenha

    volumes:
      - postgres-data:/var/lib/postgresql


  cache:

    image: redis:latest


volumes:
  postgres-data: